function par = setup()

default_params = struct(...
    'ALYX_LOGIN',  'test_user',...
    'ALYX_PWD',  '',...
    'ALYX_URL',  'https://barn.mrsic-flogel.swc.ucl.ac.uk',...
    'CACHE_DIR',  [ io.getuserdir filesep 'Downloads' filesep 'FlatIron']);
    %'FTP_DATA_SERVER',  '',...
    %'FTP_DATA_SERVER_LOGIN',  '',...
    %'FTP_DATA_SERVER_PWD',  '',...
    %'HTTP_DATA_SERVER',  '',...
    %'HTTP_DATA_SERVER_LOGIN',  '',...
    %'HTTP_DATA_SERVER_PWD',  ''...
%);
% load the current parameters and put default parameters if none exist
par = io.read.jsonpref('one_params');
if isempty(par), par=default_params; end
for ff = fieldnames(default_params)'
    cur_par = par.(ff{1});
    if isempty(cur_par), cur_par = default_params.(ff{1}); end
    % if password field, use the special prompt
    if strfind(ff{1}, 'PWD')
        disp([ff{1}])
        rep = gui_password('DialogTitle', ff{1} );
    else
        strinput = [ff{1} ': (current: ' cur_par ') '];
        rep = input(strrep(strinput,'\','\\'), 's');
    end
    if ~isempty(rep), cur_par = rep; end
    par.(ff{1}) = cur_par;
end

par = io.write.jsonpref('one_params', par);